queries:
  titulo_serie:  'title'
  nomb_capitulo: '.enlaces p'
  nomb_capitulo2: 'a.enlaces p'
  link_capitulo: 'a.enlaces'

jp-paw-series:
  anime:
    url: https://biblioteca.japan-paw.net
  anime2:
    url: https://biblioteca.japan-paw.net